name: team_25_app
description: "ChemiLens - Chemical compound detection app."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: "3.9.2"
  flutter: "3.35.3"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  image_picker: ^1.1.0
  dio: ^5.7.0

  image: ^4.1.7
  go_router: ^16.2.1
  flutter_svg: ^2.0.10+1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/app_icon.svg
    - assets/images/app_bar_icon.svg
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka-Regular.ttf
        - asset: assets/fonts/Fredoka-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Fredoka-Bold.ttf
          weight: 700
