name: team_25_app
description: "ChemiLens - Chemical compound detection app."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: "3.9.2"
  flutter: "3.35.3"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  image_picker: ^1.1.0
  dio: ^5.7.0
  http_parser: ^4.0.2
  vector_math: ^2.1.4
  path_provider: ^2.1.3
  webview_flutter: ^4.13.0

  image: ^4.1.7
  go_router: ^16.2.1
  flutter_svg: ^2.0.10+1
  flutter_localizations:
    sdk: flutter
  model_viewer_plus: ^1.9.3
  ar_flutter_plugin: ^0.7.3
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.3.4
  json_annotation: ^4.9.0
  flutter_riverpod: ^3.0.0
  riverpod_annotation: ^3.0.0
  freezed_annotation: ^3.1.0
  webview_flutter_web: ^0.2.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  freezed: ^3.2.3
  build_runner: ^2.7.1
  riverpod_generator: ^3.0.0
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/app_icon.svg
    - assets/images/app_bar_icon.svg
    - assets/fonts/
    - assets/images/
    - assets/images/app_icon2.svg
    - assets/images/camera_icon.svg

  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka-Regular.ttf
        - asset: assets/fonts/Fredoka-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Fredoka-Bold.ttf
          weight: 700
