name: team_25_app
description: "ChemiLens - Chemical compound detection app."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: "3.9.2"
  flutter: "3.35.3"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  image_picker: ^1.1.0
  dio: ^5.7.0

  image: ^4.1.7
  go_router: ^16.2.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
